{% set name = "xrt" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kklmn/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 1c4e4db630298b9af2d98bef85f8c6c13a8dbac7ad707a8ea7f680b64a0c91d2
 
build:
  # Uncomment the following line if the package is pure python and the recipe is exactly the same for all platforms.
  # It is okay if the dependencies are not built for all platforms/versions, although selectors are still not allowed.
  # See https://conda-forge.org/docs/meta.html#building-noarch-packages for more details.
  # noarch: python
  number: 0
  # If the installation is complex, or different between Unix and Windows, use separate bld.bat and build.sh files instead of this key.
  # By default, the package will be built for the Python versions supported by conda-forge and for all major OSs.
  # Add the line "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or "skip: True  # [not win]" to limit to Windows.
  # Note: --no-deps is currently required due to https://github.com/conda/conda-build/issues/3254
  # Once resolved, it should be removed.
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    # if your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - pyopencl

test:
  # Some package might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - xrt
    - xrt.backends
    - xrt.backends.raycing 
    - xrt.gui
    - xrt.gui.commons
    - xrt.gui.xrtGlow
    - xrt.gui.xrtQook

about:
  home: https://xrt.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Ray tracing and wave propagation in x-ray regime'
  description: |
    Package xrt (XRayTracer) is a python software library for ray tracing 
    and wave propagation in x-ray regime. It is primarily meant for modeling 
    synchrotron sources, beamlines and beamline elements. Includes a GUI for 
    creating a beamline and interactively viewing it in 3D.
  doc_url: https://xrt.readthedocs.io/
  dev_url: https://github.com/kklmn/xrt

extra:
  recipe-maintainers:
    - stuartcampbell
